### ISSUE TITLE
Save chat messages

### ISSUE THREAD

**Issue by kikkoi** [longy2k/obsidian-bmo-chatbot#8]
Nice the iPhone works well. Can we implement a feature to save chat messages in Markdown format to a note?

**Comment by kikkoi** [comment]
I think it would be better to have a chat history saved in JSON than note because wrong click on 'New Chat' could lead to losing chat without backup

**Comment by longy2k** [comment]
Hello @kikkoi,

I do not plan on adding multiple chat histories at this moment.  My intention for the plugin is to be a "quick-access" chatbot that can help you generate and brainstorm ideas during your note creations.

I made a few changes so that the chat history is still displayed even when you open/close Obsidian. The chat history is saved in the plugin's data folder as .txt, .html, and .json files. However, the content of the folder will be deleted every time the bot icon is clicked again.

**Comment by kikkoi** [comment]
@longy2k Thank you adding the save chat message. I see still room for improvement. History path should be added to the settings. It would have optional function for creating datetime-based path name if desired. There's no need also multiple formats, just choose file format, and should be resolved.

**Comment by longy2k** [comment]
Awesome! I will get on it. Let me know if you see any other areas for improvements.

Thanks :)

**Comment by MarioRicalde** [comment]
Would it be possible to add a function to copy all messages from the user and the responses from the bot? Bonus point if it's formatted with quotes for the bot, or something like that.

I want to have a way to save meaningful "conversations" with the AI.

**Comment by longy2k** [comment]
> Would it be possible to add a function to copy all messages from the user and the responses from the bot? Bonus point if it's formatted with quotes for the bot, or something like that.
> 
> I want to have a way to save meaningful "conversations" with the AI.

Hey @MarioRicalde,

I just released v1.6.0.

 Type `/save` in chat to save a conversation history.

Please let me know what you think :)

Thanks

**Comment by MarioRicalde** [comment]
It's perfect. Thank you so much!
